---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: networking
spec:
  secretName: wildcard-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ${SECRET_DOMAIN}
  dnsNames:
    - "*.${SECRET_DOMAIN}"
    - "${SECRET_DOMAIN}"