---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SECRET_APIKEY: |-
          {{ .apikey }}
        SECRET_EMAIL: |-
          {{ .email }}
  refreshInterval: 15m
  data:
    - secretKey: apikey
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a207bf9d-a126-42ab-ae47-b0b5003de9a7
        property: apikey
    - secretKey: email
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a207bf9d-a126-42ab-ae47-b0b5003de9a7
        property: email