---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  target:
    name: cloudflare-api-token-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        token: |-
          {{ .cloudflare_api_token }}
  refreshInterval: 15m
  data:
    - secretKey: cloudflare_api_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a207bf9d-a126-42ab-ae47-b0b5003de9a7
        property: cloudflare_token