---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SECRET_CLOUDFLARE_TOKEN: |-
          {{ .cloudflare_token }}
        SECRET_CLOUDFLARE_TUNNEL: |-
          {{ .cloudflare_tunnel }}
        SECRET_DOMAIN: |-
          {{ .domain }}
        SECRET_EMAIL: |-
          {{ .email }}
  refreshInterval: 15m
  data:
    - secretKey: cloudflare_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a207bf9d-a126-42ab-ae47-b0b5003de9a7
        property: cloudflare_token
    - secretKey: cloudflare_tunnel
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a207bf9d-a126-42ab-ae47-b0b5003de9a7
        property: cloudflare_tunnel
    - secretKey: domain
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a207bf9d-a126-42ab-ae47-b0b5003de9a7
        property: domain
    - secretKey: email
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a207bf9d-a126-42ab-ae47-b0b5003de9a7
        property: email
