---
clusterName: super-cluster
talosVersion: v1.5.4
kubernetesVersion: v1.28.2
endpoint: https://k8s.${domainName}:6443
allowSchedulingOnMasters: false
#cniConfig:
#  name: none
nodes:
  - hostname: master-microserver-81
    controlPlane: true
    ipAddress: 10.0.10.81
    installDisk: /dev/sda
#    networkInterfaces:
#      - interface: eth0
#        addresses:
#          - 10.0.10.81/24
#        routes:
#          - network: 0.0.0.0/0
#            gateway: 10.0.10.1
#        vip:
#          ip: 10.0.10.80
  - hostname: master-microserver-82
    controlPlane: true
    ipAddress: 10.0.10.82
    installDisk: /dev/sda

  - hostname: master-microserver-83
    controlPlane: true
    ipAddress: 10.0.10.83
    installDisk: /dev/sda

  - hostname: worker-microserver-84
    controlPlane: false
    ipAddress: 10.0.10.84
    installDisk: /dev/sda

  - hostname: worker-microserver-85
    controlPlane: false
    ipAddress: 10.0.10.85
    installDisk: /dev/sda

  - hostname: worker-superserver-91
    controlPlane: false
    ipAddress: 10.0.10.91
    installDisk: /dev/sdb

  - hostname: worker-superserver-92
    controlPlane: false
    ipAddress: 10.0.10.92
    installDisk: /dev/sda

  - hostname: worker-superserver-93
    controlPlane: false
    ipAddress: 10.0.10.93
    installDisk: /dev/sdb

controlPlane:
  patches:
    - |-
      machine:
        time:
          disabled: false
          servers:
            - 10.0.10.1

worker:
  patches:
    - |-
      machine:
        time:
          disabled: false
          servers:
            - 10.0.10.1